<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$(SolutionDir)GamePathFinder.props" Condition="Exists('$(SolutionDir)GamePathFinder.props')" />
	<PropertyGroup>
		<TargetFramework>net481</TargetFramework>
		<AssemblyName>ToyBox</AssemblyName>
		<Description>ToyBox</Description>
		<AppDesignerFolder>Properties</AppDesignerFolder>
		<OutputType>Library</OutputType>
		<Version>1.8.24</Version>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>preview</LangVersion>
		<Nullable>enable</Nullable>
		<RootNamespace>ToyBox</RootNamespace>
		<AnalysisLevel>preview-all</AnalysisLevel>
		<ImplicitUsings>enable</ImplicitUsings>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<RestoreAdditionalProjectSources>https://api.nuget.org/v3/index.json</RestoreAdditionalProjectSources>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
	</PropertyGroup>
	<ItemGroup>
  <Reference Include="netstandard">
    <HintPath>../w40krt/WH40KRT_Data/Managed/netstandard.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="0Harmony">
    <HintPath>../w40krt/WH40KRT_Data/Managed/0Harmony.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Ak.Wwise.Api.WAAPI">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Ak.Wwise.Api.WAAPI.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="AK.Wwise.Unity.API">
    <HintPath>../w40krt/WH40KRT_Data/Managed/AK.Wwise.Unity.API.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="AK.Wwise.Unity.API.WwiseTypes">
    <HintPath>../w40krt/WH40KRT_Data/Managed/AK.Wwise.Unity.API.WwiseTypes.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="AK.Wwise.Unity.MonoBehaviour">
    <HintPath>../w40krt/WH40KRT_Data/Managed/AK.Wwise.Unity.MonoBehaviour.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="AK.Wwise.Unity.Timeline">
    <HintPath>../w40krt/WH40KRT_Data/Managed/AK.Wwise.Unity.Timeline.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Assembly-CSharp-firstpass">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Assembly-CSharp-firstpass.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="AstarPathfindingProject">
    <HintPath>../w40krt/WH40KRT_Data/Managed/AstarPathfindingProject.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="BuildMode">
    <HintPath>../w40krt/WH40KRT_Data/Managed/BuildMode.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="BundlesBaseTypes">
    <HintPath>../w40krt/WH40KRT_Data/Managed/BundlesBaseTypes.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Cinemachine">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Cinemachine.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Code.DialogueSystem.Interfaces">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Code.DialogueSystem.Interfaces.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Code">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Code.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="ContextData">
    <HintPath>../w40krt/WH40KRT_Data/Managed/ContextData.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Core.Async">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Core.Async.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Core.Cheats.Attribute">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Core.Cheats.Attribute.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Core.Cheats">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Core.Cheats.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Core.Console">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Core.Console.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Core.Overlays">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Core.Overlays.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Core.Reflection">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Core.Reflection.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Core.RestServer.Client">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Core.RestServer.Client.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Core.RestServer.Common">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Core.RestServer.Common.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Core.RestServer">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Core.RestServer.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Core.StateCrawler">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Core.StateCrawler.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="CountingGuard">
    <HintPath>../w40krt/WH40KRT_Data/Managed/CountingGuard.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="DOTween43">
    <HintPath>../w40krt/WH40KRT_Data/Managed/DOTween43.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="DOTween46">
    <HintPath>../w40krt/WH40KRT_Data/Managed/DOTween46.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="DOTween50">
    <HintPath>../w40krt/WH40KRT_Data/Managed/DOTween50.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="DOTween">
    <HintPath>../w40krt/WH40KRT_Data/Managed/DOTween.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="DOTweenPro">
    <HintPath>../w40krt/WH40KRT_Data/Managed/DOTweenPro.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="DOTweenPro.Runtime">
    <HintPath>../w40krt/WH40KRT_Data/Managed/DOTweenPro.Runtime.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.AreaLogic.TimeOfDay">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.AreaLogic.TimeOfDay.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Blueprints.Attributes">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Blueprints.Attributes.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Blueprints.Base">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Blueprints.Base.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Blueprints.Hack">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Blueprints.Hack.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Blueprints.JsonSystem.EditorDatabase.FileDatabaseClient">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Blueprints.JsonSystem.EditorDatabase.FileDatabaseClient.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Kingmaker.Blueprints.JsonSystem.Hepers">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Blueprints.JsonSystem.Hepers.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Blueprints.JsonSystem.PropertyUtility">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Blueprints.JsonSystem.PropertyUtility.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Blueprints.JsonSystem.PropertyUtility.Helper">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Blueprints.JsonSystem.PropertyUtility.Helper.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Blueprints.OverridesManager">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Blueprints.OverridesManager.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Controllers.Enums">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Controllers.Enums.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Controllers.Interfaces">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Controllers.Interfaces.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.ElementsSystem.Interfaces">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.ElementsSystem.Interfaces.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.EntitySystem.Stats.Base">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.EntitySystem.Stats.Base.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Enums.Damage">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Enums.Damage.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Enums">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Enums.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.GameInfo">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.GameInfo.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Localization.Enums">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Localization.Enums.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.PubSubSystem.Core.Interfaces">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.PubSubSystem.Core.Interfaces.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.QA.Profiling">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.QA.Profiling.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.ResourceLinks.BaseInterfaces">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.ResourceLinks.BaseInterfaces.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.ResourceReplacementProvider">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.ResourceReplacementProvider.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.RuleSystem.Enum">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.RuleSystem.Enum.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.RuleSystem.Rules.Interfaces">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.RuleSystem.Rules.Interfaces.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Settings.ConstructionHelpers.KeyPrefix">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Settings.ConstructionHelpers.KeyPrefix.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Settings.Interfaces">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Settings.Interfaces.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Sound.Base">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Sound.Base.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Stores.DlcInterfaces">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Stores.DlcInterfaces.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Stores">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Stores.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.TextTools.Base">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.TextTools.Base.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.TextTools.Core">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.TextTools.Core.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.UI.InputSystems.Enums">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.UI.InputSystems.Enums.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.UI.Models.Log.ContextFlag">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.UI.Models.Log.ContextFlag.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.UI.Models.Log.Enums">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.UI.Models.Log.Enums.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.UI.Models.Tooltip.Base">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.UI.Models.Tooltip.Base.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.UnitLogic.Enums">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.UnitLogic.Enums.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.UnitLogic.Mechanics.Facts.Interfaces">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.UnitLogic.Mechanics.Facts.Interfaces.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Utility.Enums">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Utility.Enums.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Utility.FlagCountable">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Utility.FlagCountable.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Utility.Fsm">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Utility.Fsm.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Utility.Random">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Utility.Random.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Visual.Animation.GraphVisualizerClient">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Visual.Animation.GraphVisualizerClient.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Visual.Base">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Visual.Base.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Visual.HitSystem.Base">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Visual.HitSystem.Base.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Kingmaker.Visual.Particles.GameObjectsPooling">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Kingmaker.Visual.Particles.GameObjectsPooling.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="LocalizationShared">
    <HintPath>../w40krt/WH40KRT_Data/Managed/LocalizationShared.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="MemoryPack">
    <HintPath>../w40krt/WH40KRT_Data/Managed/MemoryPack.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Newtonsoft.Json">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Newtonsoft.Json.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Owlcat.Runtime.Core">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Owlcat.Runtime.Core.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Owlcat.Runtime.UI">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Owlcat.Runtime.UI.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Owlcat.Runtime.UniRx">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Owlcat.Runtime.UniRx.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Owlcat.Runtime.Validation">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Owlcat.Runtime.Validation.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Owlcat.Runtime.Visual">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Owlcat.Runtime.Visual.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Owlcat.ShaderLibrary.Visual">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Owlcat.ShaderLibrary.Visual.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Owlcat.Shaders.Visual">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Owlcat.Shaders.Visual.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="PFlog">
    <HintPath>../w40krt/WH40KRT_Data/Managed/PFlog.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="RogueTrader.Code.ShaderConsts">
    <HintPath>../w40krt/WH40KRT_Data/Managed/RogueTrader.Code.ShaderConsts.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="RogueTrader.Editor.ElementsDescription">
    <HintPath>../w40krt/WH40KRT_Data/Managed/RogueTrader.Editor.ElementsDescription.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="RogueTrader.GameCore">
    <HintPath>../w40krt/WH40KRT_Data/Managed/RogueTrader.GameCore.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="RogueTrader.ModInitializer">
    <HintPath>../w40krt/WH40KRT_Data/Managed/RogueTrader.ModInitializer.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="RogueTrader.NetPlayer">
    <HintPath>../w40krt/WH40KRT_Data/Managed/RogueTrader.NetPlayer.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="RogueTrader.QA.QAModeExceptionEvents">
    <HintPath>../w40krt/WH40KRT_Data/Managed/RogueTrader.QA.QAModeExceptionEvents.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="RogueTrader.SharedTypes">
    <HintPath>../w40krt/WH40KRT_Data/Managed/RogueTrader.SharedTypes.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="StatefulRandom">
    <HintPath>../w40krt/WH40KRT_Data/Managed/StatefulRandom.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="StateHasher">
    <HintPath>../w40krt/WH40KRT_Data/Managed/StateHasher.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="UberLogger">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UberLogger.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="UniRx">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UniRx.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.2D.Animation.Runtime">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.2D.Animation.Runtime.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.2D.Common.Runtime">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.2D.Common.Runtime.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.2D.IK.Runtime">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.2D.IK.Runtime.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.AI.Navigation">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.AI.Navigation.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Burst">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Burst.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Burst.Unsafe">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Burst.Unsafe.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Collections">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Collections.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Collections.LowLevel.ILSupport">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Collections.LowLevel.ILSupport.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="UnityEngine.AccessibilityModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.AccessibilityModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.AIModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.AIModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.AMDModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.AMDModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.AndroidJNIModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.AndroidJNIModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.AnimationModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.AnimationModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.ARModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.ARModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.AssetBundleModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.AssetBundleModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.AudioModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.AudioModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.ClothModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.ClothModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.ClusterInputModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.ClusterInputModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.ClusterRendererModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.ClusterRendererModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.ContentLoadModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.ContentLoadModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.CoreModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.CrashReportingModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.CrashReportingModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.DirectorModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.DirectorModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.DSPGraphModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.DSPGraphModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.GameCenterModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.GameCenterModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.GIModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.GIModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.GraphicsStateCollectionSerializerModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.GraphicsStateCollectionSerializerModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.GridModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.GridModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.HierarchyCoreModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.HierarchyCoreModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.HotReloadModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.HotReloadModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.ImageConversionModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.ImageConversionModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.IMGUIModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.IMGUIModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.InputForUIModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.InputForUIModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.InputLegacyModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.InputLegacyModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.InputModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.InputModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.JSONSerializeModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.JSONSerializeModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.LocalizationModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.LocalizationModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.MarshallingModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.MarshallingModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.MultiplayerModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.MultiplayerModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.NVIDIAModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.NVIDIAModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.ParticleSystemModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.ParticleSystemModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.PerformanceReportingModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.PerformanceReportingModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.Physics2DModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.Physics2DModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.PhysicsModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.PhysicsModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.PropertiesModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.PropertiesModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.ScreenCaptureModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.ScreenCaptureModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.ShaderVariantAnalyticsModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.ShaderVariantAnalyticsModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.SharedInternalsModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.SharedInternalsModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.SpriteMaskModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.SpriteMaskModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.SpriteShapeModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.SpriteShapeModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.StreamingModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.StreamingModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.SubstanceModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.SubstanceModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.SubsystemsModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.SubsystemsModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.TerrainModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.TerrainModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.TerrainPhysicsModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.TerrainPhysicsModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.TextCoreFontEngineModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.TextCoreFontEngineModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.TextCoreTextEngineModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.TextCoreTextEngineModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.TextRenderingModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.TextRenderingModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.TilemapModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.TilemapModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.TLSModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.TLSModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.UI">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.UI.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.UIElementsModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.UIElementsModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.UIModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.UIModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.UmbraModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.UmbraModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.UnityAnalyticsModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.UnityAnalyticsModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.UnityConnectModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.UnityConnectModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.UnityCurlModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.UnityCurlModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.UnityTestProtocolModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.UnityTestProtocolModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.UnityWebRequestAudioModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.UnityWebRequestModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.UnityWebRequestModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.UnityWebRequestTextureModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.UnityWebRequestWWWModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.VehiclesModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.VehiclesModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.VFXModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.VFXModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.VideoModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.VideoModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.VirtualTexturingModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.VirtualTexturingModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.VRModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.VRModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.WindModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.WindModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="UnityEngine.XRModule">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityEngine.XRModule.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>
  <Reference Include="Unity.Formats.Fbx.Runtime">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Formats.Fbx.Runtime.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="UnityHeapCrawler">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityHeapCrawler.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="UnityHeapEx">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityHeapEx.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.InternalAPIEngineBridge.001">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.InternalAPIEngineBridge.001.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Mathematics">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Mathematics.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.MemoryProfiler">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.MemoryProfiler.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Microsoft.GDK">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Microsoft.GDK.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Microsoft.GDK.Tools">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Microsoft.GDK.Tools.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="UnityModManagerBridge">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UnityModManagerBridge.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.PlayableGraphVisualizer">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.PlayableGraphVisualizer.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.ProBuilder.Csg">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.ProBuilder.Csg.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.ProBuilder">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.ProBuilder.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.ProBuilder.KdTree">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.ProBuilder.KdTree.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.ProBuilder.Poly2Tri">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.ProBuilder.Poly2Tri.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.ProBuilder.Stl">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.ProBuilder.Stl.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.ProGrids">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.ProGrids.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Recorder.Base">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Recorder.Base.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Recorder">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Recorder.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Rendering.LightTransport.Runtime">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Rendering.LightTransport.Runtime.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.RenderPipelines.Core.Runtime">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.RenderPipelines.Core.Runtime.Shared">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.RenderPipelines.Core.Runtime.Shared.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.RenderPipelines.Core.ShaderLibrary">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.RenderPipelines.Core.ShaderLibrary.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.RenderPipelines.GPUDriven.Runtime">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.RenderPipelines.GPUDriven.Runtime.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.ScriptableBuildPipeline">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.ScriptableBuildPipeline.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Services.Analytics">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Services.Analytics.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Services.CloudDiagnostics">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Services.CloudDiagnostics.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Services.Core.Analytics">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Services.Core.Analytics.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Services.Core.Components">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Services.Core.Components.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Services.Core.Configuration">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Services.Core.Configuration.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Services.Core.Device">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Services.Core.Device.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Services.Core">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Services.Core.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Services.Core.Environments">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Services.Core.Environments.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Services.Core.Environments.Internal">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Services.Core.Environments.Internal.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Services.Core.Internal">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Services.Core.Internal.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Services.Core.Networking">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Services.Core.Networking.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Services.Core.Registration">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Services.Core.Registration.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Services.Core.Scheduler">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Services.Core.Scheduler.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Services.Core.Telemetry">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Services.Core.Telemetry.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Services.Core.Threading">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Services.Core.Threading.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.TerrainTools">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.TerrainTools.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.TextMeshPro">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.TextMeshPro.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.Timeline">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.Timeline.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="unity-ui-extensions">
    <HintPath>../w40krt/WH40KRT_Data/Managed/unity-ui-extensions.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Unity.VisualEffectGraph.Runtime">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Unity.VisualEffectGraph.Runtime.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="UtilityAttributes">
    <HintPath>../w40krt/WH40KRT_Data/Managed/UtilityAttributes.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Utility.CodeTimer">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Utility.CodeTimer.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Utility.CommandLineArguments">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Utility.CommandLineArguments.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Utility.DisposableExtension">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Utility.DisposableExtension.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Utility.DotNetExtensions">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Utility.DotNetExtensions.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Utility.ExtendedModInfo">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Utility.ExtendedModInfo.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Utility.GameConsts">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Utility.GameConsts.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Utility.ModsInfo">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Utility.ModsInfo.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Utility.Reporting.Base">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Utility.Reporting.Base.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Utility.Rounds">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Utility.Rounds.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="Utility.UnityExtensions">
    <HintPath>../w40krt/WH40KRT_Data/Managed/Utility.UnityExtensions.dll</HintPath>
    <Private>false</Private>
  </Reference>
  <Reference Include="UnityModManager">
    <HintPath>../LocalLow/Owlcat Games/Warhammer 40000 Rogue Trader/UnityModManager/UnityModManager.dll</HintPath>
    <Private>false</Private>
    <Publicize>true</Publicize>
  </Reference>

	</ItemGroup>
	<ItemGroup>
		<None Include="Info.json" CopyToOutputDirectory="PreserveNewest" />
		<LocalizationFiles Include="Localization/*.*" />
	</ItemGroup>
	<Target Name="Deploy" AfterTargets="Build">
		<Copy SourceFiles="@(LocalizationFiles)" DestinationFolder="$(TargetDir)Localization" />
		<ItemGroup>
			<FilesToHash Include="$(TargetDir)$(AssemblyName).dll" />
		</ItemGroup>
		<GetFileHash Files="@(FilesToHash)" Algorithm="SHA256">
			<Output TaskParameter="Hash" PropertyName="DllHash" />
		</GetFileHash>
		<WriteLinesToFile File="$(TargetDir)checksum" Lines="$(DllHash)" Overwrite="true" />
		<Message Text="DLL Hash (SHA256): $(DllHash)" Importance="High" />

		<ItemGroup>
			<Files Include="$(TargetDir)/**/*.*" />
		</ItemGroup>

		<Copy SourceFiles="@(Files)" DestinationFiles="@(Files->'$(RogueTraderData)/UnityModManager/0$(AssemblyName)0/%(RecursiveDir)%(Filename)%(Extension)')" />
		<ZipDirectory SourceDirectory="$(MSBuildProjectDirectory)/$(OutputPath)" DestinationFile="$(MSBuildProjectDirectory)/$(OutputPath)/../$(AssemblyName)-$(Version).zip" Overwrite="true" />
	</Target>
  <!-- <ItemGroup> -->
  <!--   <FrameworkReference Include="Microsoft.NETFramework.ReferenceAssemblies.net481" /> -->
  <!-- </ItemGroup> -->
	<ItemGroup>
		<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="*-*" PrivateAssets="all" />
		<PackageReference Include="System.Collections" Version="4.3.0" PrivateAssets="all" />
		<PackageReference Include="System.Runtime.Numerics" Version="4.3.0" PrivateAssets="all" />
		<PackageReference Include="System.IO.Compression" Version="4.3.0" PrivateAssets="all" />
		<PackageReference Include="System.IO.Compression.ZipFile" Version="4.3.0" PrivateAssets="all" />
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" IncludeAssets="build; contentfiles" Version="0.4.2" PrivateAssets="all" />
		<PackageReference Include="MicroUtils.HarmonyAnalyzers" IncludeAssets="runtime; build; native; contentfiles; analyzers" Version="*-*" PrivateAssets="all" />
		<PackageReference Include="ToyBox.BuildTools" IncludeAssets="analyzers; build; compile" Version="1.1.9.5" PrivateAssets="all" />
	</ItemGroup>
	<Target Name="UpdateLocalizationFiles" BeforeTargets="Deploy">
		<UpdateLocalizationTask LocalizationDirectoryPath="$(SolutionDir)ToyBox/Localization" AssemblyPath="$(TargetDir)$(AssemblyName).dll" />
	</Target>
</Project>
